#!/bin/bash

export IMPORTANT_WORK_DIR="$HOME/acme/important"
export UNIMPORTANT_WORK_DIR="$HOME/acme/unimportant"

alias cd-important="cd $IMPORTANT_WORK_DIR"
alias cd-unimportant="cd $UNIMPORTANT_WORK_DIR"

